language: python

python:
  - "2.7"

services: mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="travis_ci.travis_ci_settings"
    - PYTHONPATH="/home/travis/build/k2mno5/CS-411"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.11.6 DB=mysql

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
#  - pip install -q -r requirements.txt

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py syncdb --noinput

#command to run the test suite
script:
  - python manage.py test
